[features]
seeds = false
skip-lint = false
[programs.localnet]
convergence = "4irSQbid9JUAkhUf5yhnx5o3EgaY3saAErK9oQtPURHo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/thomas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
